version: "3.9"

services:
  web:
    image: my-status-page
    ports:
      - "8080:80"

  logger:
    image: busybox
    command: sh -c "while true; do echo 'Logger: service is running'; sleep 5; done"